name: 15-minute-cron
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://beach-importer.vercel.app/api/import' \
          --header 'Authorization: Bearer ${{ secrets.IMPORTER_API_KEY }}'
